### ISSUE TITLE
weekly report fetched instead of daily report

### ISSUE THREAD

**Issue by cellularmitosis** [kirbyt/appdailysales#7]
Interestingly, my daily call to appdailysales.py resulted in apple's weekly report being downloaded (starts with 'S_W' instead of 'S_D').  Nothing has changed in my cron job, so I'm assuming Apple is mucking with their HTML.

**Comment by lbast** [comment]
Same issue for me. :-(

**Comment by ghost** [comment]
Me to

**Comment by boyi** [comment]
me too

**Comment by kirbyt** [comment]
This has been fixed thanks to @boyi and @staufman.
